FROM node:latest

# Proje dizinini /app olarak belirliyoruz
WORKDIR /app

# package.json ve package-lock.json dosyalarını kopyala (bağımlılıkları doğru bir şekilde yüklemek için)
COPY package.json package-lock.json ./

# src dizinindeki kodları konteynıra kopyala
COPY ./src ./src

# Eğer .next dizini veya diğer oluşacak dosyalar varsa, bunları da kopyalayabilirsiniz
COPY ./.next ./.next

# Uygulama 3000 portunu dinleyecek
EXPOSE 3000

# Docker container başlatıldığında bağımlılıkları yükle ve ardından uygulamayı başlat
CMD npm install && npm run build && npm start
