FROM node:22.14.0            # Node.js 22.14.0 sürümünü kullanıyoruz
WORKDIR /app                 # Çalışma dizinini /app olarak ayarlıyoruz
COPY package.json package-lock.json ./  # package.json ve package-lock.json dosyalarını /app dizinine kopyalıyoruz
RUN npm install              # Bağımlılıkları yüklemek için npm install komutunu çalıştırıyoruz
COPY . .                     # Uygulama dosyalarını /app dizinine kopyalıyoruz
EXPOSE 3000                  # 3000 portunu expose ediyoruz
CMD ["npm", "run", "start"]  # Next.js uygulamasını başlatıyoruz
