# Node.js imajı
FROM node:latest

# Proje dizinini /app olarak belirliyoruz
WORKDIR /app

# next-app klasöründen package.json ve package-lock.json dosyalarını kopyala (bağımlılıkları doğru bir şekilde yüklemek için)
COPY next-app/package.json next-app/package-lock.json ./

# npm install komutunu çalıştırarak bağımlılıkları yükle
RUN npm install

# next-app klasöründeki kodları konteynıra kopyala
COPY next-app/ ./

# Container başlatıldığında uygulamayı başlatacak komut
CMD ["npm", "run", "dev"]

# Uygulama 3000 portunu dinleyecek
EXPOSE 3000
