# Next.js için base image
FROM node:18-alpine

# Uygulama dizini
WORKDIR /app

# package.json ve package-lock.json dosyalarını kopyala
COPY package*.json ./

# Bağımlılıkları yükle
RUN npm install

# Uygulama dosyalarını kopyala
COPY . .

# Uygulama build işlemi
RUN npm run build

# Uygulama çalıştırma komutu
CMD ["npm", "start"]

# Portu expose et
EXPOSE 3000
