version: '3.8'

services:
  livestream:
    container_name: live
    build: .
    restart: unless-stopped
    ports:
      - "1935:1935"  # RTMP Yayın Portu
      - "8080:8080"  # HLS için HTTP Servisi
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Nginx config dosyası
      - ./hls:/hls  # HLS dosyalarının kaydedileceği klasör
    networks:
      - test_network  # Kendi oluşturduğumuz özel network

networks:
  custom_network:
    driver: bridge  # Yeni bir bridge network oluşturuluyor, Traefik'e bağımlı değil
