version: "3.8"

services:
  nginx-rtmp:
    container_name: nginx-rtmp
    build:
      context: ./nginx

    restart: unless-stopped
    ports:
      - "1935:1935"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./hls:/hls:rw
    networks:
      - proxy

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    working_dir: /app
    networks:
      - proxy
    

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "5000:5000"  # API dışarı açıldı
    networks:
      - proxy
networks:
  proxy:
    external: true # Traefik'in kullandığı ağ
