version: "3.8"

services:
  livestream:
    container_name: live
    build: .
    restart: unless-stopped
    ports:
      - "1935:1935" # RTMP Yayın Portu açık
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Nginx config dosyası
      - ./hls:/hls # HLS dosyalarının kaydedileceği klasör
    networks:
      - proxy
    # RTMP servisine Traefik labelleri eklenmedi, sadece iç ağda çalışacak

  nextjs:
    container_name: next-app
    build:
      context: ./next-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./next-app:/app
      - ./hls:/app/public/hls # HLS dosyalarını Next.js içine mount et
    working_dir: /app
    command: "npm run start"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`hls.sametak.com`)"
      - "traefik.http.routers.web.entrypoints=https"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
      - "traefik.http.routers.web.tls.certresolver=cloudflare"
      - "traefik.http.routers.web.service=web"

networks:
  proxy:
    external: true # Traefik'in kullandığı ağ
