version: "3.8"

services:
  nginx-rtmp:
    container_name: nginx-rtmp
    build: 
       context: ./next-app

    restart: unless-stopped
    ports:
      - "1935:1935"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./next-app/tmp/:/hls
    networks:
      - proxy

  nextjs:
    container_name: next-app
    build:
      context: ./next-app
    ports:
      - "3001:3000"
    volumes:
      - ./hls:/app/tmp/hls
    working_dir: /app
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`hls.sametak.com`)"
      - "traefik.http.routers.web.entrypoints=https"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
      - "traefik.http.routers.web.tls.certresolver=cloudflare"
      - "traefik.http.routers.web.service=web"

networks:
  proxy:
    external: true # Traefik'in kullandığı ağ
