# Use Node.js official image
FROM node:latest

# Set the working directory
WORKDIR /usr/src/app

# Copy the package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy the source code
COPY . .

# Expose port
EXPOSE 5000

# Run the app
CMD ["node", "server.js"]
