name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  
  deploy:
    runs-on: ubuntu-latest
  

    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3

      - name: SSH Key Kur ve Bağlan
        run: |
          # SSH anahtarını kur ve bağlantıyı test et
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: SSH Key Git Config
        run: |
          # Git için SSH anahtarını yapılandır
          git config --global core.sshCommand "ssh -i ~/.ssh/id_rsa"

      - name: Sunucuya Bağlan ve Güncelle
        run: |
          # Sunucuya bağlan ve en son sürümü çek, ardından Docker Compose ile güncellemeleri yap
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /docker_volumes/sametak
            git pull origin main
            docker compose down
            docker compose up -d --build
            docker compose up -d
          EOF

      - name: Servisleri kontrol et
        run: |
          # Docker Compose ile tüm servisleri başlat
          sleep 10
          curl -f https://hls.sametak.com || exit 1  # Next.js servisini kontrol et

      - name: Cleanup (SSH Temizleme)
        run: rm -rf ~/.ssh
