name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  
  test:
    runs-on: ubuntu-latest
    needs: test_connection
    if: success()

    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3

      - name: Docker Build Test İmajı
        run: |
          # Docker imajını oluştur
          docker build -t sametak-test .

      - name: Docker Test Ağı Oluştur
        run: |
          # Docker proxy ağı oluştur
          docker network create proxy

      - name: Docker Compose İle Servisleri Başlat
        run: |
          # Docker Compose ile tüm servisleri başlat
          docker compose up -d

      - name: Servislerin Çalıştığını Kontrol Et
        run: |
          # Servislerin doğru çalışıp çalışmadığını kontrol et
          sleep 10  # Servislerin başlatılmasını bekle
          curl -f http://localhost:3000 || exit 1  # Next.js servisini kontrol et

      - name: Temizleme (Docker Compose Down)
        run: |
          # Docker Compose ile başlatılan tüm konteynerleri kapat
          docker compose down

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3

      - name: SSH Key Kur ve Bağlan
        run: |
          # SSH anahtarını kur ve bağlantıyı test et
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: SSH Key Git Config
        run: |
          # Git için SSH anahtarını yapılandır
          git config --global core.sshCommand "ssh -i ~/.ssh/id_rsa"

      - name: Sunucuya Bağlan ve Güncelle
        run: |
          # Sunucuya bağlan ve en son sürümü çek, ardından Docker Compose ile güncellemeleri yap
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /docker_volumes/sametak
            git pull origin main
            docker compose down
            docker build -t sametak-app .
            docker compose up -d
          EOF

      - name: Docker Compose İle Servisleri Başlat
        run: |
          # Docker Compose ile tüm servisleri başlat
          docker compose up -d

      - name: Cleanup (SSH Temizleme)
        run: rm -rf ~/.ssh
