name: Test

on:
  push:
    branches:
      - main

jobs:
 test_connection:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Keys and Test Connection
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo 'SSH bağlantısı başarılı!'"
  test:
    runs-on: ubuntu-latest
    needs: test_connection
    if: success()

    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3

      - name: Docker Build Test
        run: docker build -t sametak-test .

      - name: Docker Test Network Oluştur
        run: docker network create proxy

      - name: Docker Compose Up
        run: docker compose up -d

      - name: Servislerin Çalıştığını Kontrol Et
        run: |
          sleep 10  # Servislerin açılmasını bekle
          curl -f http://localhost:8080/hls || exit 1

      - name: Temizleme (Cleanup)
        run: docker compose down

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()
    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3

      - name: Sunucuya Bağlan ve Güncelle
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /docker_volumes/sametak
            git pull origin main
            docker compose down
            docker build -t sametak-app .
            docker compose up -d
