name: Test

on:
  push:
    branches:
      - main  # sadece main'e push yapıldığında çalışacak

jobs:
  test:
    runs-on: ubuntu-latest  # GitHub'ın sağladığı Ubuntu makinesi

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Docker Build Test
        run: docker build -t sametak-test .
    
      - name: Docker Compose Up (Test için)
        run: docker compose -f docker-compose.yml -f docker-compose.override.yml up -d

      - name: Test Servisleri Çalıştır
        run: |
          sleep 10  # Servislerin açılmasını bekle
          curl -f http://localhost:8080/hls || exit 1

      - name: Cleanup
        run: docker compose down
