name: Deploy

on:
  push:
    branches:
      - main  # Sadece main branch'e push yapınca çalışır

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3

      - name: Sunucuya Bağlan ve Güncelle
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /docker_volumes/sametak
            git pull origin main
            docker-compose down
            docker build -t sametak-app .
            docker-compose up -d
